# Generated by Django 4.2.8 on 2024-03-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='winner',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
