# Generated by Django 4.2.8 on 2024-03-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='election',
            name='start_date',
        ),
        migrations.AddField(
            model_name='election',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
