# Generated by Django 4.2.8 on 2024-03-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_election_end_date_remove_election_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.CharField(default='CR', max_length=255),
        ),
    ]
