# Generated by Django 4.2.8 on 2024-03-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_vote_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.IntegerField(max_length=255),
        ),
    ]
