# Generated by Django 4.2.8 on 2024-03-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_vote_candidate_alter_vote_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.IntegerField(),
        ),
    ]
