# Generated by Django 4.2.8 on 2024-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_vote_candidate_alter_vote_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='calculated_votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=255)),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
