# Generated by Django 4.2.8 on 2024-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_calculated_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='vote_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=255)),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='calculated_votes',
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.CharField(max_length=255),
        ),
    ]
