# Generated by Django 4.2.8 on 2024-03-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_vote_count_delete_calculated_votes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vote_count',
        ),
    ]
