# Generated by Django 4.2.8 on 2024-04-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_delete_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.TextField(default='A POLL'),
        ),
    ]
